#eureka:
#  client:
#    serviceUrl:
 #     defalutZone: http://localhost:8761/eureka/
#server:
#  port: 8763
spring:
  application:
    name: eureka-client
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: ZH124578
  profiles:
    active: client1
---
spring:
  profiles: client1
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
---
spring:
  profiles: client2
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/