package com.example.entity;

import java.io.Serializable;

/**
 * 
 * User
 * 数据库表：user_
 */
public class User implements Serializable {

    /**
     * 
     * 表字段 : user_.id_
     */
    private Integer id;

    /**
     * 
     * 表字段 : user_.username_
     */
    private String username;

    /**
     * 
     * 表字段 : user_.password_
     */
    private String password;

    /**
     * 
     * 表字段 : user_.nickname_
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:user_.id_
     *
     * @return user_.id_, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:user_.id_
     *
     * @param id the value for user_.id_, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:user_.username_
     *
     * @return user_.username_, 
     */
    public String getUsername() {
        return username;
    }

    /**
     * 设置  字段:user_.username_
     *
     * @param username the value for user_.username_, 
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * 获取  字段:user_.password_
     *
     * @return user_.password_, 
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置  字段:user_.password_
     *
     * @param password the value for user_.password_, 
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 获取  字段:user_.nickname_
     *
     * @return user_.nickname_, 
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * 设置  字段:user_.nickname_
     *
     * @param nickname the value for user_.nickname_, 
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}